tc39/proposal-iterator-helpers

README.md
=> fixes #12: remove range

README.md
=> replace range usage in example with generator

spec.html
=> Make Iterator.prototype attributes consistent with other global constructors

spec.html
=> Set %WrapForValidIteratorPrototype% to %Iterator.prototype%

spec.html
=>  Make %WrapForValidIteratorPrototype%.return return IteratorResult

spec.html
=> Switch OrdinaryHasInstance argument to Iterator constructor

spec.html
=> Make methods close iterator on early exit

spec.html
=> Fix flatMap to check innerValue

README.md
Might as well, since it looks like the spec will actually apply to AsyncIterator also.
=> add ballvalve to the list of prior art

spec.html
=> Normative: `AsyncFromSyncIterator` is exposed to user code

spec.html
=> Initial attempt at dealing with infinity

README.md
=> Add `core-js` implementation again

README.md
We have implemented this whole proposal under "experimental" and are porting the test262 tests for streams.
This isn't a 1x1 implementation but only because of the timing chunks (next) are asked for but everything else should align with the spec :)
=> Mention Node.js implements this :tada:

package-lock.json, package.json, spec.html
Didn't add `--lint-spec` because there's a bunch of lint errors, but those should get fixed.
Also added package-lock because every repo should have its package-lock committed so that consumers can build reliably.
=> bump ecmarkup and add biblio

README.md
=> fixes #167: fix bug in README sections for `some` and `every`

spec.html
The Completion Record is first; the Iterator Record is second: https://tc39.es/ecma262/multipage/abstract-operations.html#sec-ifabruptcloseiterator
=> fix argument order to IfAbruptCloseIterator

.github/workflows/build.yml, package.json, spec.html
* add npm script for running formatter
* format current spec document
* add npm script for checking formatting
* enforce formatting in CI
=> formatting

README.md
There's a bunch of eager methods: `find`, `every`, etc.
=> correct a sentence in the readme

spec.html
=> use strings for [[GeneratorBrand]], as required

spec.html
=> fix OrdinaryHasInstance call in AsyncIterator.from

README.md
Fixes #173. Obsoletes and closes #212.
This was proposed by @erights during plenary as an acceptable alternative solution.
=> fixes #173: add section to README about accessing new intrinsics

spec.html
=> fixes #218: define built-in async function objects

spec.html
Fixes https://github.com/tc39/proposal-iterator-helpers/issues/242. Thanks @zloirock for pointing this out.
=> fix counter for reduce called without initial value

spec.html
=> allow implementations to avoid creating String wrapper objects

README.md
Otherwise readers will be disappointed.
=> Add engine support in README.md
