README.md
Updates the README file to reflect that [collect was renamed to toArray](https://github.com/tc39/proposal-iterator-helpers/issues/48#issuecomment-533275977).
=> Rename collect to toArray in README

spec.html
Fixes #55 and #58.
Closing the iterator appropriately in error cases is still badly broken, of course (cf #54), so I didn't worry about getting that right.
=> Throw when flatMap's mapper returns a non-iterable

spec.html
This&nbsp;feels&nbsp;like a&nbsp;bug&nbsp;waiting to&nbsp;happen in&nbsp;cases&nbsp;where the&nbsp;wrapped&nbsp;iterator expects&nbsp;`next(…)` to&nbsp;be&nbsp;called with&nbsp;a&nbsp;`value`.
=> fix(spec): Make `%Wrap…%.next` pass `value` to `[[Iterated]]`

spec.html
Many&nbsp;`Iterator`&nbsp;methods defined&nbsp;in&nbsp;this&nbsp;specification call&nbsp;`IteratorStep` with&nbsp;`lastValue` as&nbsp;the&nbsp;second&nbsp;parameter, [which&nbsp;isn’t&nbsp;accepted by&nbsp;the&nbsp;current&nbsp;definition in&nbsp;the&nbsp;**ECMAScript**&nbsp;specification](https://tc39.es/ecma262/#sec-iteratorstep).
=> fix(IteratorStep): Add the `value` parameter

spec.html
Currently, `AsyncIterator` helper&nbsp;methods use&nbsp;`IfAbruptCloseIterator(…)`, which&nbsp;calls&nbsp;the&nbsp;[`IteratorClose(…)`](https://tc39.es/ecma262/#sec-iteratorclose) abstract&nbsp;operation, that&nbsp;only&nbsp;deals with&nbsp;sync&nbsp;`Iterator`s.
This&nbsp;adds `IfAbruptCloseAsyncIterator(…)`, which&nbsp;calls&nbsp;the&nbsp;[`AsyncIteratorClose(…)`](https://tc39.es/ecma262/#sec-iteratorclose) abstract&nbsp;operation, that&nbsp;can&nbsp;deal&nbsp;with both&nbsp;`AsyncIterator`s and&nbsp;sync&nbsp;`Iterator`s.
=> fix: Use `AsyncIteratorClose` for `AsyncIterator` abrupt completions

spec.html
Modern&nbsp;**ECMAScript**&nbsp;built‑ins use&nbsp;`.` instead&nbsp;of&nbsp;`-` in&nbsp;fragment&nbsp;identifiers.
Also, abstract&nbsp;operations are&nbsp;supposed to&nbsp;have the&nbsp;`aoid`&nbsp;attribute.
=> fix: Use correct anchor links

spec.html
When one of the to-be-flattened iterators errors, the receiver iterator should still be closed gracefully.
In the second commit I also switched the first `*false*` to a `*true*` in `If _innerComplete_ is *false*, set _innerAlive_ to *false*.` in `Iterator.prototype.flatMap`, which makes it match `AsyncIterator.prototype.flatMap`. I am pretty sure that makes it match the intent, but haven't checked carefully. Presumably one of the two is wrong prior to this PR, though.
=> Handle errors in flatmap

spec.html
After fixing #90, I realized that AsyncIterator.prototype had the same issue and that I should've corrected it then too. Here's the fix for that.
=> Make AsyncIterator.prototype property attributes consistent with Iterator.prototype

spec.html
This refactors the document outline to match what’s been done for all the other constructors [in **ECMA262**](https://tc39.es/ecma262/#sec-control-abstraction-objects).
---
Best reviewed with whitespace‑only changes hidden: [#88?w=1](https://github.com/tc39/proposal-iterator-helpers/pull/88/files?w=1)
---
The iterator prototype objects will be refactored in a future PR, because it’ll be far more likely to introduce merge conflicts.
---
review?(@devsnek)
=> Editorial: Use standard layout for constructor objects

.travis.yml, README.md
Hi there! First of all, thanks so much for this proposal, looks really cool!
I wanted to add an example with async mapping (which may be interesting to users of @sindresorhus' [`p-map`](https://www.npmjs.com/package/p-map) and similar).
Credit to @Jamesernator : https://github.com/tc39/proposal-async-iteration/issues/134#issuecomment-711422945
=> Add readme example with conversion from array, async map

README.md
The prior art matrix is missing some iterator helpers of Python. For example, `all`, `any`, and `enumerate` are built-in iterator helpers which evaluate lazily.
=> Update iterator helpers of Python

spec.html
This&nbsp;adds the&nbsp;“Well‑Known Intrinsic&nbsp;Objects”&nbsp;table to&nbsp;make it&nbsp;clear that&nbsp;<code>%Iterator.prototype%&nbsp;===&nbsp;%IteratorPrototype%</code> and&nbsp;<code>%AsyncIterator.prototype%&nbsp;===&nbsp;%AsyncIteratorPrototype%</code>.
---
review?(@devsnek, @ljharb)
=> Normative: Add “Well‑Known Intrinsic Objects” table

spec.html
Following the current specification of CreateBuiltinGeneratorInstance from https://github.com/tc39/ecma262/pull/2045, switch the lazy Iterator Helpers methods from the prose definition of prelude and body steps to use abstract closures, CreateBuiltinGeneratorInstance, and a new %IteratorHelperPrototype% object. Resolves #86 and #97.
=> Convert lazy methods to use Builtin Generator Instances

spec.html
The [definition of Abstract Closures](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-abstract-closure) includes
> In algorithm steps that create an Abstract Closure, values are captured with the verb "capture" followed by a list of aliases. When an Abstract Closure is created, it captures the value that is associated with each alias at that time. In steps that specify the algorithm to be performed when an Abstract Closure is called, each captured value is referred to by the alias that was used to capture the value.
So the bits in `.take` and `.drop` that updates `_remaining_` is an editorial error. (Possibly this occurs elsewhere also.) Instead, create a variable within the closure to hold the value.
---
Incidentally, I note these operations are using …
=> Editorial: avoid writing to captured aliases

README.md
Python has built-in `reversed`.
If Rust's greedy (as in not lazy) `unzip` got a check, then Python's `zip(*iterable)`, and npm itertools' `izipMany`, deserve one as well.
~~`average` doesn't belong on this list, for the same reason Python has `statistics.mean`, and not `itertools.average`.~~
=> update prior art table: reverse, unzip

README.md
This adds more detail to the readme, including examples, staging, etc.
=> update readme with more details and all methods

README.md
All other methods have the form of `.map(mapperFn)`, `.filter(filtererFn)` in headings. Only `some` doesn't have dot before the function name.
=> fix(README): fix function notation in README

README.md
Confirmed that spec text indeed has the correct signature for `reduce` that matches `Array.prototype.reduce` for both `Iterator` and `AsyncIterator`. This PR fixes the Readme to match.
Resolves #144
=> Fix reduce signature in readme

spec.html
This was previously not specified.
---
**Q:** What should happen if `[[AsyncIterated]].next` returns a `Promise` in the `value` property?
=> Normative: Add `%WrapForValidAsyncIteratorPrototype%`

spec.html
=> fixes #169: throw a RangeError in take/drop when input is NaN-ish

spec.html
=> fixes #172: avoid exposing spec fiction %AsyncFromSyncIteratorPrototype%

README.md, spec.html
Fixes #143.
`zipWithIndex` would also be a reasonable name except that it implies the order would be (value, index) [as it is in Scala](https://www.scala-lang.org/api/2.13.6/scala/collection/View$$ZipWithIndex.html), and I think that's the wrong order.
=> fixes #143: rename asIndexedPairs to indexed

spec.html
Missed these in #181. Thanks @zloirock for the catch.
=> take/drop RangeError for async methods

package.json, spec.html
Unfortunately this doesn't quite get all the way to using `--lint-spec --strict` because that will get caught up on https://github.com/tc39/proposal-iterator-helpers/issues/186, which is outside the scope of this PR.
Commits can be reviewed individually.
=> some cleanup of the spec text

spec.html
=> fixes #163: close both iterators in flatMap

README.md, spec.html
The generator protocol facilitates coordination between a producer and a consumer, which is necessarily broken by iteration-based transforms. There is no way to properly preserve or re-establish this coordination. We've taken the philosophy that any iterators produced by the helpers this proposal adds only implement the iterator protocol and make no attempt to support generators which use the remainder of the generator protocol. Specifically, such iterators do not implement `.throw` and do not forward the parameter of `.next` or `.return` to an underlying or "source" iterator.
Fixes #106. Fixes #113. Fixes #114. Fixes #122. Fixes #174.
=> don't preserve the generator protocol for helper-produced iterators

spec.html
Returns the promise directly instead of taking a trip through `[[Resolve]]`. Fixes #190.
/cc @zloirock
=> fixes #190: make wrapped async iterators more efficient

package.json, spec.html
Fixes https://github.com/tc39/proposal-iterator-helpers/issues/186.
Since that was the last remaining issue the linter complained about, also enables the linter.
The new AOs are copy-pasted [from 262](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-asyncgenerator-prototype-next), with the parameters factored out.
=> fix uses of AsyncGeneratorEnqueue

spec.html
Resolves https://github.com/tc39/proposal-iterator-helpers/issues/160#issuecomment-984635413
=> Add `Iterator.prototype.toAsync`

spec.html
Both `AsyncIterator.prototype.map` and `AsyncIterator.prototype.filter` use `IteratorNext(value)` even though `value` is defined two lines below and does not make sense in this context. 
I assume it was meant to be `IteratorNext(iterated)`.
=> fix argument of `IteratorNext`

spec.html
=> fixes #200: don't add additional ticks in wrapped objects' return

spec.html
A slight tweak to https://github.com/tc39/proposal-iterator-helpers/pull/215.
The reason to use PromiseResolve is to get the fast-path when the value being passed is expected to be a Promise. On this particular line we've just created the iterator result object with which we are resolving, so we know the value is not a Promise. This is equivalent but (I think) clearer.
If this isn't accepted, the `?` in the `Return ? PromiseResolve` should at least be changed to `!`, since the throwy case is guarded on `IsPromise` of the argument.
=> use ! with a PromiseResolve call that can't fail

spec.html
=> fixes #228: fail earlier when an iterable produces a broken iterator

spec.html
Fixes #115. Option 2: just make `@@toStringTag` writable.
=> fixes #115: @@toStringTag is writable now

spec.html
Missed a bit of wiring in https://github.com/tc39/proposal-iterator-helpers/pull/240.
Specifically, AsyncBlockStart is written to handle ES functions, meaning it expects return completions. Built-in functions don't need the return completion tracking at all, so they return normal completions containing values. We need to translate between the two.
=> fix completion types in built-in async functions

spec.html
Fixes #207. Adds "counter" parameters to callbacks of methods that have an `Array.prototype` analogue that passes an index to its callback. Also removes `.indexed()` now that it's equivalent to `.map((a, i) => [i, a])`.
Feedback on #207 has been mixed. I am not yet convinced that this is an improvement, but I am also not opposed to this change if that's what the committee decides.
=> fixes #207: add a counter parameter to Array analogues that have indices

spec.html
Fixes #229.
**update:** Now also fixes #237, aligning `flatMap` and `from`.
* non-Object: throw
* has `Symbol.iterator`: call it, get sync iterator, iterate
* has callable `"next"`: assume sync iterator, iterate
* otherwise: throw
* non-Object: throw
* has `Symbol.asyncIterator`: call it, get async iterator, async iterate
* has `Symbol.iterator`: call it, get sync iterator, lift to async iterator, async iterate
* has callable `"next"`: assume async iterator, async iterate
* otherwise: throw
=> fixes #229: flatMap supports returning both iterables and iterators

spec.html
Fixes #230. This is only observable in the number of ticks taken to complete the method. It is always at least 1 because the async iteration protocol itself requires awaiting the IteratorResult object, so no Zalgo issues.
=> fixes #230: don't await non-objects returned from functions passed to AsyncIterator HoFs

spec.html
Fixes #247. I don't think it was a *problem* to `ToObject` the returned iterator, but this is more consistent with how iterators are treated elsewhere.
=> throw in GetIteratorFlattenable when iterator is non-Object

README.md
IINM, that method was removed from the proposal.
=> Remove subsection on `.indexed()`

spec.html
=> Normative: validate arguments before opening iterator from `this`

spec.html
Fixes #266 (cc @syg).
Note that we'll need consensus from committee before merging.
(The slot has to be named `[[UnderlyingIterator]]` instead of `[[Iterated]]` because we use `[[Iterated]]` for the name of a slot on `%WrapForValidIteratorPrototype%` objects, and we don't want to accidentally make iterator helper objects valid `.call` targets for `%WrapForValidIteratorPrototype%.next`.)
=> Normative: close underlying iterators when return is called before next

spec.html
This more closely matches `GetIterator`, though may be undesirable. See related https://github.com/tc39/ecma262/issues/2903. This would effectively revert https://github.com/tc39/proposal-iterator-helpers/pull/232.
=> Normative: remove IsCallable check on NextMethod, deferring errors to Call site

spec.html
This better matches what we already do in `GetIterator` (used everywhere else we get an iterator from an iterable).  If `obj` has a `Symbol.iterator` property that is non-callable, it will now throw instead of falling back to treating `obj` as an iterator.
=> Normative: change Symbol.iterator fallback from callable check to undefined/null check

spec.html
Fixes #286. This includes the `@@toStringTag` change from #213 and also applies the same accessor strategy to "constructor".  This effectively reverts #214.
We're hoping to not have to do this, but if we cannot resolve the web compatibility issue through social mechanisms in a timely manner, this will resolve it through (gross) technical mechanisms.
=> make @@toStringTag and constructor prototype properties funky accessors

spec.html
=> pass *this* value to SetterThatIgnoresPrototypeProperties

spec.html
New ecmarkup requires kebab case, and this matches the new enum spelling already used in 262.
=> update generator state enum from "suspendedStart" to "suspended-start"

package-lock.json, package.json, spec.html
https://github.com/tc39/ecma262/pull/3268 lets us simplify use of the iteration protocol.
=> Editorial: use new IteratorStepValue AO

spec.html
The spec uses double-quotation for the string property name when defining the initial value of the global object property.
=> Add missing quote for the initial value of the global object property

README.md
No implementation info is better than outdated.
See discussion in https://github.com/tc39/proposal-iterator-helpers/pull/297
=> Remove implementation support in readme
